version: "2"
services:
  api:
    image: pock8s/inventory-api:dev
    ports:
      - "5000:5000"
    volumes:
      # Remaps the volume for live editing
      - .:/app
    env_file:
      - .env
    # Run the flask server in development mode
    command: bin/flask-dev.sh

  migrate:
    image: pock8s/inventory-api:dev
    volumes:
      - .:/app
    command: bin/flask-upgrade.sh

  test:
    image: pock8s/inventory-api:dev
    volumes:
      - .:/app
    command: bin/flask-test.sh